default_sessions = ["verify-markup", "spell-check"]
top_level_targets = []

[github_actions.docker-publish]
[github_actions.resync_piped]
[github_actions.update_licence]
[github_actions.upgrade_locks]
[github_actions.verify_locks]
